import { Link } from "react-router-dom";
import { heroMetrics } from "../../data/metrics";
import { MetricCard } from "../common/MetricCard";

export function HeroSection() {
  return (
    <section className="mx-auto max-w-7xl px-6 pb-20 pt-16 md:pb-28 md:pt-24">
      <div className="grid gap-12 lg:grid-cols-[1.15fr_0.85fr]">
        <div>
          <p className="text-sm uppercase tracking-[0.45em] text-cyan-100/75">PhD Research Portfolio · Bharat Babaso Mane</p>
          <h1 className="mt-6 font-display text-5xl leading-tight text-white md:text-7xl">
            AI Writes Code. Humans Write Code.
            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-cyan-300 to-violet-300 mt-1">
              Can Either Be Judged Automatically?
            </span>
          </h1>
          <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">
            Whether written by a developer or generated by an AI agent, code quality still needs to be
            <strong className="text-white"> measured, explained, and verified</strong>. This thesis builds
            explainable deep learning tools that assess readability at every level —
            from a single identifier name to the developer behind the codebase.
          </p>
          <div className="mt-8 flex flex-wrap gap-4">
            <Link
              to="/demo"
              className="rounded-full bg-cyan-300 px-6 py-3 text-sm font-semibold text-slate-950 transition hover:bg-cyan-200"
            >
              ⚡ Try Live Demo
            </Link>
            <Link
              to="/thesis-story"
              className="rounded-full border border-white/15 bg-white/5 px-6 py-3 text-sm font-semibold text-white transition hover:bg-white/10"
            >
              The Research Story
            </Link>
            <Link
              to="/papers"
              className="rounded-full border border-white/15 bg-white/5 px-6 py-3 text-sm font-semibold text-white transition hover:bg-white/10"
            >
              View Papers
            </Link>
          </div>
        </div>
        <div className="grid gap-4 self-start">
          {heroMetrics.map((metric) => (
            <MetricCard key={metric.label} metric={metric} />
          ))}
        </div>
      </div>
    </section>
  );
}
